### ISSUE TITLE
Tuya Key missing or incorrect 

### ISSUE THREAD

**Issue by Yovarithia** [SeydX/homebridge-star-projector#13]
Basically I get this whenever I start the homebridge (which is run on a raspberry pi. I already tried troubleshooting with other bugs I found here but it didn’t work. I tried with 2 different projects on tuya’s site but the plugin always complains that my api secret is wrong. I don’t really know how to resolve this so I’d be happy if you could explain why this is happening. Should I try with another tuya account?

**Comment by bonzijuse** [comment]
you must use the tuya api wizard to get the client secret. install tuya-cli in your terminal and run `tuya-cli wizard` the program should tell you what information to input and after that you should get a client secret
