### ISSUE TITLE
Error 'Key is missing or incorrect.' for a confirmed working api/key combo

### ISSUE THREAD

**Issue by gitothy** [SeydX/homebridge-star-projector#4]
**Describe the bug**
Plugin configured per instructions:

>         {
>            "name": "StarProjector",
>            "debug": true,
>            "projectors": [
>                {
>                    "name": "GalaxyProjector_Tuya",
>                    "tuyaId": "aaaaaaaaaaaaaaa",
>                    "tuyaKey": "kkkkkkkkkkkkkkkkkkk"
>                }
>            ],
>            "platform": "StarProjector"
>        },

The **api id** and **key** used are working fine for the HomeAssistant Tuya v2 integration.  I have also tried my email address for the value of tuyaID with the api key but getting the same error.

I've checked through the api authorisation steps you've linked here on github and it's identical for the homeassistant integration.  I am using an approved 'Individual Developer' API account w/ country/region of United Kingdom.

All related lines from HomeBridge log:

`[8/27/2021, 2:49:42 PM] [StarProjector] Initializing StarProjector platform...`
`[8/27/2021, 2:49:42 PM] [StarProjector] GalaxyProjector_Tuya: An error occured during setting up the device!`
`[8/27/2021, 2:49:42 PM] [StarProjector] Key is missing or incorrect.`

**Additional context**
Debugging is enabled and was hoping I could work this one out myself.  Is there any way for me to get more info on this error?

**### Update: Looked at your code.  Seems it's failing in the tuyapi part before your plugin really starts.  Would this be better logged over there?**

**Comment by cyberb0b** [comment]
Did you run the npm i @tuyapi/cli -g  command like described on the page?

Did you , after that, run the "tuya-cli wizard"  command and used the device ID from the iot tuya device id in this wizard? 
Then it will generate a device and key id for the projector. 

YOu need to enter those into homebridge, not the credentials from the tuya website.

**Comment by gitothy** [comment]
Ah - missed that step, many thanks for highlighting.  All sorted now :)
