### ISSUE TITLE
find() timed out during startup

### ISSUE THREAD

**Issue by tfohlmeister** [SeydX/homebridge-star-projector#5]
I receive the following error during homebridge startup:
`StarProjector: An error occured during connecting to Tuya API: find() timed out. Is the device powered on and the ID or IP correct? - Retry in 60s`

Credentials from tuya-cli:
```
[
  {
    name: 'Panamalar-Smart Star Projector',
    id: '***',
    key: '***'
  }
]
```
I configured the plugin as following:

```
{
            "name": "StarProjector",
            "projectors": [
                {
                    "name": "StarProjector",
                    "tuyaId": "ID_FROM_ABOVE",
                    "tuyaKey": "KEY_FROM_ABOVE",
                    "color": true,
                    "laser": true,
                    "starRotation": true,
                    "scenes": [
                        {
                            "active": false
                        },
                        {
                            "active": false
                        }
                    ]
                }
            ],
            "platform": "StarProjector"
        }
```

Is there any way to debug this? Looking at the source code it seems my homebridge instance can't access the tuya server at all..?!

**Comment by tfohlmeister** [comment]
Probably a problem in the upstream library or in my setup. Closing this now.

**Comment by ScharV** [comment]
@tfohlmeister could you solve the issue? having the same problem with two setups and can't find a way to get it working

**Comment by tfohlmeister** [comment]
@ScharV Unfortunately not, I returned the projector by now (also because of this).
